//задания на уровень
const tasks = [
 	task1 = {task:``,
			sec:30,
			sizeFormatAnswer: `9rem`,
			formatAnswer:"",
			pict:"./Images/01.jpg"},
	task2 = {task:``,
 			formatAnswer:``,
			sec:30,
 			pict:"./Images/02.jpg"},
	task3 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/03.jpg"},
	task4 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/04.jpg"},
	task5 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/05.jpg"},
	task6 = {task:``,
			sec:30,
			sizetask:``,
			sizeFormatAnswer: `7rem`,
			formatAnswer:``,
			pict:"./Images/06.jpg"},
	task7 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/07.jpg"},
 	task8 = {task:``,
			sec:30,
			sizeFormatAnswer: `9rem`,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/08.jpg"},
	task9 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/09.jpg"},
	task10 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/10.jpg"},
	task11 = {task:``,
			sec:30,
			sizetask:``,
			sizeFormatAnswer: `7rem`,
			formatAnswer:``,
			pict:"./Images/11.jpg"},
	task12 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/12.jpg"},
 	task13 = {task:``,
			sec:30,
			sizeFormatAnswer: `9rem`,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/13.jpg"},
	task14 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/14.jpg"},
	task15 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/15.jpg"},
 	task16 = {task:``,
			sec:30,
			formatAnswer:``,
			pict:"./Images/16.jpg"},
	task17 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/17.jpg"},
	task18 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/18.jpg"},
	task19 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/19.jpg"},
	task20 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/20.jpg"}		

];
	



const answers = [
  	task1 = {
			sec:12, formatAnswer:"",
			task:"<br><br> Кто сильнее вас",
			pict:""},
	task2 = {
			sec:12, formatAnswer:"",
 			task:`<br><br>Завтра`,
 			pict:""},
	task3 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Мудр`,
			pict:""},
	task4 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Без удовольствия`,
			pict:""},
	task5 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Памятных шрамов`,
			pict:""},
	task6 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Нужных`,
			pict:""},
	task7 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Была влюблена`,
			pict:""},
	task8 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Любил`,
			pict:""},
	task9 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Подхалимствуй`,
			pict:""},
	task10 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Несчастье`,
			pict:""},
	task11 = {
			sec:12, formatAnswer:"",
 			task:`<br><br>Звенит будильник`,
 			pict:""},
	task12 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Повторимо`,
			pict:""},
	task13 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Воспитанный`,
			pict:""},
	task14 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Хороший знак`,
			pict:""},
	task15 = {
			sec:12, formatAnswer:"",
			task:`<br><br>В краю родном`,
			pict:""},
	task16 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Сердце герцогини`,
			pict:""},
	task17 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Пирожник`,
			pict:""},
	task18 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Веревочка`,
			pict:""},
	task19 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Пистолета`,
			pict:""},
	task20 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Плетень`,
			pict:""}
];
			

