//задания на уровень
const tasks = [
 	task1 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: `9rem`,
			formatAnswer:"",
			pict:"./images/01.jpg"},
	task2 = {task:`<br><br>`,
 			formatAnswer:``,
			sec:30,
 			pict:"./images/02.jpg"},
	task3 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/03.jpg"},
	task4 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/04.jpg"},
	task5 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/05.jpg"},
	task6 = {task:`<br><br>`,
			sec:30,
			sizetask:`<br><br>`,
			sizeFormatAnswer: `7rem`,
			formatAnswer:``,
			pict:"./images/06.jpg"},
	task7 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/07.jpg"},
 	task8 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: `9rem`,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/08.jpg"},
	task9 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/09.jpg"},
	task10 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/10.jpg"},
	task11 = {task:`<br><br>`,
			sec:30,
			sizetask:`<br><br>`,
			sizeFormatAnswer: `7rem`,
			formatAnswer:``,
			pict:"./images/11.jpg"},
	task12 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/12.jpg"},
 	task13 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: `9rem`,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/13.jpg"},
	task14 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/14.jpg"},
	task15 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/15.jpg"},
 	task16 = {task:`<br><br>`,
			sec:30,
			formatAnswer:``,
			pict:"./images/16.jpg"},
	task17 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/17.jpg"},
	task18 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/18.jpg"},
	task19 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/19.jpg"},
	task20 = {task:`<br><br>`,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:`<br><br>`,
			formatAnswer:``,
			pict:"./images/20.jpg"}		

];
	



const answers = [
  	task1 = {
			sec:12, formatAnswer:"",
			task:"<br><br> Кто сильнее вас",
			pict:""},
	task2 = {
			sec:12, formatAnswer:"",
 			task:`<br><br>Завтра`,
 			pict:""},
	task3 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Мудр`,
			pict:""},
	task4 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Без удовольствия`,
			pict:""},
	task5 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Памятных шрамов`,
			pict:""},
	task6 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Нужных`,
			pict:""},
	task7 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Была влюблена`,
			pict:""},
	task8 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Любил`,
			pict:""},
	task9 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Подхалимствуй`,
			pict:""},
	task10 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Несчастье`,
			pict:""},
	task11 = {
			sec:12, formatAnswer:"",
 			task:`<br><br>Звенит будильник`,
 			pict:""},
	task12 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Повторимо`,
			pict:""},
	task13 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Воспитанный`,
			pict:""},
	task14 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Хороший знак`,
			pict:""},
	task15 = {
			sec:12, formatAnswer:"",
			task:`<br><br>В краю родном`,
			pict:""},
	task16 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Сердце герцогини`,
			pict:""},
	task17 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Пирожник`,
			pict:""},
	task18 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Веревочка`,
			pict:""},
	task19 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Пистолета`,
			pict:""},
	task20 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Плетень`,
			pict:""}
];
			

