//задания на уровень
const tasks = [
 	task1 = {task:``,
			sec:30,
			sizeFormatAnswer: `9rem`,
			formatAnswer:"",
			pict:"./Images/01.jpg"},
	task2 = {task:``,
 			formatAnswer:``,
			sec:30,
 			pict:"./Images/02.jpg"},
	task3 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/03.jpg"},
	task4 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/04.jpg"},
	task5 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/05.jpg"},
	task6 = {task:``,
			sec:30,
			sizetask:``,
			sizeFormatAnswer: `7rem`,
			formatAnswer:``,
			pict:"./Images/06.jpg"},
	task7 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/07.jpg"},
 	task8 = {task:``,
			sec:30,
			sizeFormatAnswer: `9rem`,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/08.jpg"},
	task9 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/09.jpg"},
	task10 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/10.jpg"},
	task11 = {task:``,
			sec:30,
			sizetask:``,
			sizeFormatAnswer: `7rem`,
			formatAnswer:``,
			pict:"./Images/11.jpg"},
	task12 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/12.jpg"},
 	task13 = {task:``,
			sec:30,
			sizeFormatAnswer: `9rem`,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/13.jpg"},
	task14 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/14.jpg"},
	task15 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizetask:``,
			formatAnswer:``,
			pict:"./Images/15.jpg"}	

];
	



const answers = [
  	task1 = {
			sec:12, formatAnswer:"",
			task:"<br><br> Стабилизатор напряжения",
			pict:""},
	task2 = {
			sec:12, formatAnswer:"",
 			task:`<br><br>Кошелек для монет`,
 			pict:""},
	task3 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Ручной эспандер`,
			pict:""},
	task4 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Открывающаяся игрушка`,
			pict:""},
	task5 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Фен`,
			pict:""},
	task6 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Шагометр`,
			pict:""},
	task7 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Пылесос`,
			pict:""},
	task8 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Микрофон`,
			pict:""},
	task9 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Весы`,
			pict:""},
	task10 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Компостер`,
			pict:""},
	task11 = {
			sec:12, formatAnswer:"",
 			task:`<br><br>Плойки для волос`,
 			pict:""},
	task12 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Соковыжималка`,
			pict:""},
	task13 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Открывашка-штопор`,
			pict:""},
	task14 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Бритва`,
			pict:""},
	task15 = {
			sec:12, formatAnswer:"",
			task:`<br><br>Коньки`,
			pict:""}
];
			

